# Generated by Django 4.2.3 on 2023-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hostel_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee_payment",
            name="due_date",
            field=models.DateField(default="2023-10-10"),
        ),
    ]
