# Generated by Django 4.2.3 on 2023-09-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Hostel_app", "0002_alter_fee_payment_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("room_rent", models.FloatField(default=0)),
                ("mess_bill", models.FloatField(default=0)),
                ("amount", models.FloatField(default=0)),
                ("status", models.IntegerField(default=0)),
                ("paid_by", models.CharField(max_length=100)),
                ("paid_date", models.DateField(null=True)),
                ("payment", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Hostel_app.student",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Fee_payment",
        ),
    ]
