from django.urls import path

from Hostel_app import views, adminviews, studentviews, parentviews, wardenviews

urlpatterns=[
    path('', views.hostapp, name='hostapp'),
    path('hostlogin',views.hostlogin,name='hostlogin'),
    path('log_out',views.log_out,name='log_out'),
    path('signupreg',views.signupreg,name='signupreg'),
    path('admin_dash',views.admin_dash,name='admin_dash'),
    path('student_signupreg',views.student_signupreg,name='student_signupreg'),
    path('warden_signupreg',views.warden_signupreg,name='warden_signupreg'),
    path('parent_signupreg',views.parent_signupreg,name='parent_signupreg'),
    path('student_dash',views.student_dash,name='student_dash'),
    path('warden_dash',views.warden_dash,name='warden_dash'),
    path('parent_dash',views.parent_dash,name='parent_dash'),
    path('addhostel', adminviews.addhostel, name='addhostel'),
    path('viewhostel',adminviews.viewhostel, name='viewhostel'),
    path('updatehostel/<int:id>/', adminviews.updatehostel, name='updatehostel'),
    path('deletehostel/<int:id>/', adminviews.deletehostel, name='deletehostel'),
    path('addfood', adminviews.addfood, name='addfood'),
    path('viewfood',adminviews.viewfood, name='viewfood'),
    path('updatefood/<int:id>/', adminviews.updatefood, name='updatefood'),
    path('deletefood/<int:id>/', adminviews.deletefood, name='deletefood'),
    path('addnotification', adminviews.addnotification, name='addnotification'),
    path('viewnotification',adminviews.viewnotification, name='viewnotification'),
    path('updateotification/<int:id>/', adminviews.updatenotification, name='updatenotification'),
    path('deletenotification/<int:id>/', adminviews.deletenotification, name='deletenotification'),
    path('addwarden', adminviews.addwarden, name='addwarden'),
    path('viewwarden',adminviews.viewwarden, name='viewwarden'),
    path('updatewarden/<int:id>/', adminviews.updatewarden, name='updatewarden'),
    path('deletewarden/<int:id>/', adminviews.deletewarden, name='deletewarden'),
    path('viewregistration',adminviews.viewregistration, name='viewregistration'),
    path('approve_student/<int:id>/', adminviews.approve_student, name='approve_student'),
    path('reject_student/<int:id>/', adminviews.reject_student, name='reject_student'),
    path('approve_parent/<int:id>/', adminviews.approve_parent, name='approve_parent'),
    path('reject_parent/<int:id>/', adminviews.reject_parent, name='reject_parent'),
    path('add_fee', adminviews.add_fee, name='add_fee'),
    path('load_bill', adminviews.load_bill, name='load_bill'),
    path('view_fee', adminviews.view_fee, name='view_fee'),
    path('view_bill_detail/<int:id>/', adminviews.view_bill_detail, name='view_bill_detail'),





    path('view_hostel',studentviews.view_hostel, name='view_hostel'),
    path('view_food',studentviews.view_food, name='view_food'),
    path('view_notification',studentviews.view_notification,name='view_notification'),
    path('base1',studentviews.base1,name='base1'),
    path('add_review', studentviews.add_review, name='add_review'),
    path('view_review', studentviews.view_review, name='view_review'),
    path('update_review/<int:id>/', studentviews.update_review, name='update_review'),
    path('delete_review/<int:id>/', studentviews.delete_review, name='delete_review'),
    path('viewreview_admin',adminviews.viewreview_admin, name='viewreview_admin'),
    path('add_complaint', studentviews.add_complaint, name='add_complaint'),
    path('view_complaint', studentviews.view_complaint, name='view_complaint'),
    path('view_complaintadmin', adminviews.view_complaintadmin, name='view_complaintadmin'),
    path('complaint_reply/<int:id>/', adminviews.complaint_reply, name='complaint_reply'),
    path('add_bookroom',studentviews.add_bookroom,name='add_bookroom'),
    path('view_bookingstatus',studentviews.view_bookingstatus, name='view_bookingstatus'),
    path('attendance_view',studentviews.attendance_view, name='attendance_view'),
    path('view_fee_st',studentviews.view_fee_st, name='view_fee_st'),
    path('view_bill_detail_s/<int:id>/',studentviews.view_bill_detail_s, name='view_bill_detail_s'),
    path('checkout_session/<int:id>/', studentviews.checkout_session, name='checkout_session'),
    path('pay_success/', studentviews.pay_success, name='pay_success'),
    path('pay_cancel', studentviews.pay_cancel, name='pay_cancel'),





    path('viewbookingstatus_admin',adminviews.viewbookingstatus_admin, name='viewbookingstatus_admin'),
    path('confirm_booking/<int:id>/',adminviews.confirm_booking, name='confirm_booking'),
    path('reject_booking/<int:id>/',adminviews.reject_booking, name='reject_booking'),
    path('add_attendance',adminviews.add_attendance,name='add_attendance'),
    path('mark/<int:id>/',adminviews.mark,name='mark'),
    path('viewattendance_admin',adminviews.viewattendance_admin,name='viewattendance_admin'),
    path('day_attendance/<date>/',adminviews.day_attendance,name='day_attendance'),
    path('view_hostelparent',parentviews.view_hostelparent, name='view_hostelparent'),
    path('view_foodparent',parentviews.view_foodparent, name='view_foodparent'),
    path('view_notifiparent',parentviews.view_notifiparent, name='view_notifiparent'),
    path('bookroom_parent',parentviews.bookroom_parent, name='bookroom_parent'),
    path('bookroom_parent',parentviews.bookroom_parent, name='bookroom_parent'),
    path('bookstatus_par',parentviews.bookstatus_par, name='bookstatus_par'),
    path('view_attendance',parentviews.view_attendance, name='view_attendance'),
    path('wardenview_par',parentviews.wardenview_par, name='wardenview_par'),
    path('add_complaint_par',parentviews.add_complaint_par, name='add_complaint_par'),
    path('view_complaint_par',parentviews.view_complaint_par, name='view_complaint_par'),
    path('addreview_par',parentviews.addreview_par, name='addreview_par'),
    path('view_review_par',parentviews.view_review_par, name='view_review_par'),
    path('base2',parentviews.base2, name='base2'),
    path('studentview_ward',wardenviews.studentview_ward, name='studentview_ward'),
    path('parentview_ward',wardenviews.parentview_ward, name='parentview_ward'),
    path('add_leaveapp',studentviews.add_leaveapp, name='add_leaveapp'),
    path('view_leaveapp',studentviews.view_leaveapp, name='view_leaveapp'),
    path('leave_view',wardenviews.leave_view, name='leave_view'),
    path('approve_leave/<int:id>/',wardenviews.approve_leave, name='approve_leave'),
    path('reject_leave/<int:id>/',wardenviews.reject_leave, name='reject_leave'),
    path('in_outmark',wardenviews.in_outmark, name='in_outmark'),
    path('view_inout',wardenviews.view_inout, name='view_inout'),
    path('update_in_reg/<int:id>/',wardenviews.update_in_reg, name='update_in_reg'),
    path('register_inout_status/<int:id>/',wardenviews.register_inout_status, name='register_inout_status'),
    path('in_out_view',studentviews.in_out_view, name='in_out_view'),
    path('view_in_out_reg',parentviews.view_in_out_reg, name='view_in_out_reg'),
    path('view_fee_p',parentviews.view_fee_p, name='view_fee_p'),
    path('view_bill_detail_p/<int:id>/',parentviews.view_bill_detail_p, name='view_bill_detail_p'),
    path('par_checkout_session/<int:id>/', parentviews.par_checkout_session, name='par_checkout_session'),
    path('par_pay_success/', parentviews.par_pay_success, name='par_pay_success'),
    path('par_pay_cancel', parentviews.par_pay_cancel, name='par_pay_cancel'),



    path('delete_profile',parentviews.delete_profile, name='delete_profile'),

]